### ISSUE TITLE
World failed to delete

### ISSUE THREAD

**Issue by tsingyayin** [Kihsomray/CyberWorldReset-Standard#1]
I am using version 0.6.1 of the plugin on the 1.19.2-purpur server, and I am using version 4.3.1 and 4.3.2 snapshot versions of the multiverse core plugin. However, I encountered a problem. The plugin cannot delete the world normally, so I cannot continue to reset the world.
Among the information I found on the console, only the following contents are related to them (I set the reset interval of the world to five minutes, so it can be seen that this Exception occurred during the second attempt to reset)
* [14:59:00] [Server thread/INFO]: [Multiverse-Core] World 's_world' was unloaded from Multiverse.
[14:59:00] [Server thread/INFO]: The world "s_world" failed to delete!
[14:59:38] [Server thread/INFO]: TsingYayin issued server command: /world s_world
[15:04:00] [Server thread/WARN]: [CWR] Task #3868 for CyberWorldReset v0.6.1 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getEnvironment()" because the return value of "net.zerotoil.cyberworldreset.objects.WorldObject.getWorld()" is null
	at net.zerotoil.cyberworldreset.objects.WorldObject.tpPlayersAway(WorldObject.java:231) ~[CyberWorldReset-0.6.1.jar:?]
	at net.zerotoil.cyberworldreset.objects.WorldObject.regenWorld(WorldObject.java:141) ~[CyberWorldReset-0.6.1.jar:?]
	at net.zerotoil.cyberworldreset.objects.TimedReset$MyTimeTask$1.run(TimedReset.java:182) ~[CyberWorldReset-0.6.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

When I actually checked the corresponding folder of the world named "s_world" mentioned above, I found that most of the files have been deleted, but one .mca file in the poi folder has not been deleted. Since I was the only one on the server during the test, I presume that this file should be occupied during deletion due to some unload error, so it could not be removed correctly.

**Comment by Kihsomray** [comment]
Hey, thanks for reporting this. I could provide a dev build that will send an error log (stack trace) that might help with a solution. Would you like this?

**Comment by tsingyayin** [comment]
Thank you for your review. I stopped the plug-in after the problem occurred, and tried to regenerate the world using the regen command of multiverse core, but I still encountered similar problems. So I thought about using the old version of multiverse core, and the problem was alleviated. However, the regenerated world will encounter an error in reading and writing paperfileiothread when using it. Since this error is also related to reading and writing files, I personally tend to suspect that there are some problems with paper or the multiverse core plug-in itself. That is to say, it seems that the problem I have encountered so far cannot be clearly confirmed to be caused by your plug-in. I will continue to observe the problem : )

The error reported by the paperfileiothread I encountered is as follows:
* [04:32:24] [Paper RegionFile IO Thread/ERROR]: [com.destroystokyo.paper.io.PaperFileIOThread] Failed to write chunk data for task: Task for world: 's_world' at 61,48 poi: true, hash: 630872151
java.nio.file.AccessDeniedException: .\s_world\poi\r.1.1.mca
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:298) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:357) ~[?:?]
	at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:459) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:432) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.getRegionFile(RegionFileStorage.java:101) ~[?:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.write(RegionFileStorage.java:288) ~[?:?]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.a(PoiManager.java:483) ~[?:?]
	at net.minecraft.server.level.ServerLevel$1.writeData(ServerLevel.java:331) ~[?:?]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:556) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[purpur-1.19.2.jar:git-Purpur-1758]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[purpur-1.19.2.jar:git-Purpur-1758]

**Comment by MatthewMerrill** [comment]
Sorry to necro this issue but -- I tried writing a similar plugin recently. I don't have links handy but I had some trouble deleting world files shortly after teleporting players away. If I manually tp-d away and waited a little bit, the world would delete okay.

I read somewhere online suggesting that this only happens on Windows, and that was consistent with my finding for my plugin -- when I moved it to a linux machine I stopped observing this behavior.

This is to say, this issue may be OS-specific and require weakreferences/magical workarounds for windows.
